import type { AiTradeContext, AiManagementDecision } from "@/lib/ai-manager";
import { manageTradesBatchWithAi } from "@/lib/ai-batch-manager";

type Raw=any; type Side="LONG"|"SHORT"; type C={time:number;open:number;high:number;low:number;close:number};
type BaseCandidate={side:Side;entry:number;stop:number;take:number;risk:number;time:number;baselineR:number;path:C[];h1f:Side|null;score:number;majorSweep:boolean};
type Active={c:BaseCandidate;currentStop:number;partialRealized:number;remaining:number;done:boolean;resultR:number;events:any[];cursor:number;aiChecks:number};
type Signals={favorableBos:boolean;adverseBos:boolean;favorableDisplacement:boolean;adverseDisplacement:boolean;defense:boolean;adverseRejection:boolean;zoneDefense:boolean;protectedSwing:number|null;strongFavorable:boolean;strongAdverse:boolean};
type ManagementEvent={index:number;label:"INVALIDACAO_FORTE"|"DETERIORACAO_APOS_MFE"|"SWING_PROTEGIDO"};

function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);if(Number.isFinite(b)&&Number.isFinite(a))return(b+a)/2;if(Number.isFinite(b))return b;if(Number.isFinite(a))return a;return null;}
function norm(r:Raw):C|null{const open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice),s=r?.snapshotTimeUTC??r?.snapshotTime,time=s?Date.parse(String(s).endsWith("Z")?s:`${s}Z`):NaN;if([open,high,low,close].some(x=>x===null)||!Number.isFinite(time))return null;return{time,open:open!,high:high!,low:low!,close:close!};}
function agg(src:C[],m:number){const z=m*60000,out:C[]=[];let k=-1,c:C|null=null;for(const x of src){const b=Math.floor(x.time/z)*z;if(b!==k){if(c)out.push(c);k=b;c={...x,time:b};}else if(c){c.high=Math.max(c.high,x.high);c.low=Math.min(c.low,x.low);c.close=x.close;}}if(c)out.push(c);return out;}
function swings(a:C[],n=2){const hs:number[]=[],ls:number[]=[];for(let i=n;i<a.length-n;i++){let h=true,l=true;for(let j=1;j<=n;j++){if(a[i].high<=a[i-j].high||a[i].high<=a[i+j].high)h=false;if(a[i].low>=a[i-j].low||a[i].low>=a[i+j].low)l=false;}if(h)hs.push(i);if(l)ls.push(i);}return{hs,ls};}
function flow(a:C[]):Side|null{const h=a.slice(-80),s=swings(h);if(s.hs.length<2||s.ls.length<2)return null;const H1=h[s.hs.at(-1)!].high,H0=h[s.hs.at(-2)!].high,L1=h[s.ls.at(-1)!].low,L0=h[s.ls.at(-2)!].low;return H1>H0&&L1>L0?"LONG":H1<H0&&L1<L0?"SHORT":null;}
function opposite(side:Side):Side{return side==="LONG"?"SHORT":"LONG";}
function fib(a:C[],side:Side,p:number){const x=a.slice(-48);if(x.length<12)return false;const hi=Math.max(...x.map(c=>c.high)),lo=Math.min(...x.map(c=>c.low)),r=hi-lo;if(r<=0)return false;const x61=side==="LONG"?hi-r*.618:lo+r*.618,x786=side==="LONG"?hi-r*.786:lo+r*.786;return p>=Math.min(x61,x786)&&p<=Math.max(x61,x786);}
function fvg(a:C[],side:Side,p:number){for(let i=Math.max(2,a.length-24);i<a.length;i++){const x=a[i-2],z=a[i];if(side==="LONG"&&x.high<z.low&&p>=x.high&&p<=z.low)return true;if(side==="SHORT"&&x.low>z.high&&p<=x.low&&p>=z.high)return true;}return false;}
function displacementAt(a:C[],i:number,side:Side){if(i<10)return false;const c=a[i],prior=a.slice(i-10,i),b=prior.map(x=>Math.abs(x.close-x.open)).sort((x,y)=>x-y),med=b[Math.floor(b.length/2)]||0,body=Math.abs(c.close-c.open),rng=c.high-c.low||1,dir=side==="LONG"?c.close>c.open:c.close<c.open;return dir&&body>med*1.5&&body/rng>.58;}
function displacement(a:C[],side:Side){return a.length>10&&displacementAt(a,a.length-1,side);}
function obValidated(a:C[],side:Side,p:number){for(let i=a.length-5;i>=Math.max(2,a.length-30);i--){const c=a[i];if(side==="LONG"&&c.close<c.open){for(let j=i+1;j<=Math.min(i+4,a.length-1);j++)if(displacementAt(a,j,"LONG")&&a[j].close>c.high&&p>=c.low&&p<=c.high)return true;}if(side==="SHORT"&&c.close>c.open){for(let j=i+1;j<=Math.min(i+4,a.length-1);j++)if(displacementAt(a,j,"SHORT")&&a[j].close<c.low&&p>=c.low&&p<=c.high)return true;}}return false;}
function sweepLocal(a:C[],side:Side,n=10){if(a.length<n+1)return false;const s=a.at(-1)!,q=a.slice(-n-1,-1),lo=Math.min(...q.map(x=>x.low)),hi=Math.max(...q.map(x=>x.high));return side==="LONG"?s.low<lo&&s.close>lo:s.high>hi&&s.close<hi;}
function candle(a:C[],side:Side){if(a.length<2)return false;const c=a.at(-1)!,p=a.at(-2)!,body=Math.abs(c.close-c.open),rng=c.high-c.low||1;const engulf=side==="LONG"?c.close>c.open&&p.close<p.open&&c.close>=p.open&&c.open<=p.close:c.close<c.open&&p.close>p.open&&c.close<=p.open&&c.open>=p.close;const pin=side==="LONG"?(Math.min(c.open,c.close)-c.low)>body*1.6&&body/rng<.5:(c.high-Math.max(c.open,c.close))>body*1.6&&body/rng<.5;return engulf||pin;}
function bos(a:C[],side:Side,n=5){if(a.length<n+1)return false;const c=a.at(-1)!,q=a.slice(-n-1,-1);return side==="LONG"?c.close>Math.max(...q.map(x=>x.high)):c.close<Math.min(...q.map(x=>x.low));}
function m1ok(a:C[],side:Side,t:number){if(a.length<8||!a.at(-1)||a.at(-1)!.time<t-120000)return false;return bos(a,side,4)||candle(a,side)||sweepLocal(a,side,7)||displacement(a,side);}
function inWindow(t:number){const d=new Date(t),m=d.getUTCHours()*60+d.getUTCMinutes();return m<=1110;}
function dayKey(t:number){const d=new Date(t);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate());}
function prevDayLevels(all:C[],i:number){const today=dayKey(all[i].time);let hi=-Infinity,lo=Infinity,found=false,prev:number|null=null;for(let j=i-1;j>=0;j--){const dk=dayKey(all[j].time);if(dk===today)continue;if(!found){found=true;prev=dk;}else if(dk!==prev)break;hi=Math.max(hi,all[j].high);lo=Math.min(lo,all[j].low);}return found?{hi,lo}:null;}
function sessionLevels(all:C[],i:number){const today=dayKey(all[i].time),asiaEnd=today+6*3600000;let asiaHi=-Infinity,asiaLo=Infinity,midOpen:number|null=null;for(let j=i;j>=0;j--){if(dayKey(all[j].time)!==today)break;if(all[j].time<asiaEnd){asiaHi=Math.max(asiaHi,all[j].high);asiaLo=Math.min(asiaLo,all[j].low);}midOpen=all[j].open;}return{asiaHi,asiaLo,midOpen};}
function sweepLevel(c:C,side:Side,levels:number[]){return levels.some(l=>Number.isFinite(l)&&(side==="LONG"?c.low<l&&c.close>l:c.high>l&&c.close<l));}
function rAt(c:C,side:Side,en:number,risk:number){return side==="LONG"?(c.close-en)/risk:(en-c.close)/risk;}
function baselineOutcome(path:C[],side:Side,en:number,stop:number,take:number,risk:number){for(const c of path){const sh=side==="LONG"?c.low<=stop:c.high>=stop,th=side==="LONG"?c.high>=take:c.low<=take;if(sh)return side==="LONG"?(stop-en)/risk:(en-stop)/risk;if(th)return 2;}const last=path.at(-1);return last?Math.max(-1,Math.min(2,rAt(last,side,en,risk))):0;}
function protectedSwing(a:C[],side:Side,current:number){const x=a.slice(-24),s=swings(x,2);if(side==="LONG"){for(let k=s.ls.length-1;k>=0;k--){const p=x[s.ls[k]].low;if(p<current)return p;}}else{for(let k=s.hs.length-1;k>=0;k--){const p=x[s.hs[k]].high;if(p>current)return p;}}return null;}
function eventSignals(a:C[],side:Side):Signals{const current=a.at(-1)?.close??0,opp=opposite(side),favorableBos=bos(a,side,5),adverseBos=bos(a,opp,5),favorableDisplacement=displacement(a,side),adverseDisplacement=displacement(a,opp),defense=candle(a,side)||sweepLocal(a,side,7),adverseRejection=candle(a,opp)||sweepLocal(a,opp,7),zoneDefense=fvg(a,side,current)||obValidated(a,side,current),protectedLevel=protectedSwing(a,side,current);const strongFavorable=(favorableBos||favorableDisplacement)&&(defense||zoneDefense||protectedLevel!==null),strongAdverse=adverseBos&&adverseDisplacement&&(adverseRejection||!zoneDefense);return{favorableBos,adverseBos,favorableDisplacement,adverseDisplacement,defense,adverseRejection,zoneDefense,protectedSwing:protectedLevel,strongFavorable,strongAdverse};}

function buildCandidates(raw5:Raw[],raw1:Raw[],limit:number){const m5=raw5.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m1=raw1.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m15=agg(m5,15),h1=agg(m5,60);const out:BaseCandidate[]=[];let blocked=-1,p15=-1,p1=-1,pm1=-1;for(let i=120;i<m5.length-50&&out.length<limit;i++){const s=m5[i],ct=s.time+300000;while(p15+1<m15.length&&m15[p15+1].time<=ct-900000)p15++;while(p1+1<h1.length&&h1[p1+1].time<=ct-3600000)p1++;while(pm1+1<m1.length&&m1[pm1+1].time<=s.time)pm1++;if(i<=blocked||p15<40||p1<25||pm1<8||!inWindow(s.time))continue;const a5=m5.slice(Math.max(0,i-120),i+1),a15=m15.slice(Math.max(0,p15-100),p15+1),a1=h1.slice(Math.max(0,p1-100),p1+1),aM1=m1.slice(Math.max(0,pm1-25),pm1+1),h1f=flow(a1),pd=prevDayLevels(m5,i),sess=sessionLevels(m5,i);for(const side of ["LONG","SHORT"] as Side[]){const levels=side==="LONG"?[pd?.lo??NaN,sess.asiaLo,sess.midOpen??NaN]:[pd?.hi??NaN,sess.asiaHi,sess.midOpen??NaN];const majorSweep=sweepLevel(s,side,levels);let score=0;if(majorSweep)score+=28;if(sweepLocal(a5,side,8))score+=10;if(displacement(a5,side))score+=16;if(bos(a5,side))score+=16;if(obValidated(a5,side,s.close)||obValidated(a15,side,s.close))score+=12;if(fvg(a5,side,s.close)||fvg(a15,side,s.close))score+=10;if(candle(a5,side))score+=8;if(h1f&&h1f!==side)score+=6;if(fib(a5,side,s.close))score+=10;if(score<58||!m1ok(aM1,side,s.time))continue;const en=m5[i+1].open,stop=side==="LONG"?Math.min(...a5.slice(-10).map(c=>c.low)):Math.max(...a5.slice(-10).map(c=>c.high)),risk=Math.abs(en-stop);if(risk<=0||risk/en>.008)continue;const take=side==="LONG"?en+risk*2:en-risk*2,path=m5.slice(i+1,Math.min(i+49,m5.length));const c:BaseCandidate={side,entry:en,stop,take,risk,time:s.time,baselineR:0,path,h1f,score,majorSweep};c.baselineR=baselineOutcome(path,side,en,stop,take,risk);out.push(c);blocked=i+1;break;}}
return out;}

function mfeUntil(c:BaseCandidate,index:number){return Math.max(...c.path.slice(0,index+1).map(x=>rAt({...x,close:c.side==="LONG"?x.high:x.low},c.side,c.entry,c.risk)));}
function maeUntil(c:BaseCandidate,index:number){return Math.min(...c.path.slice(0,index+1).map(x=>rAt({...x,close:c.side==="LONG"?x.low:x.high},c.side,c.entry,c.risk)));}
function eventContext(a:Active,index:number,label:string){const c=a.c,bar=c.path[index],before=c.path.slice(Math.max(0,index-18),index+1),r=rAt(bar,c.side,c.entry,c.risk),mfe=mfeUntil(c,index),mae=maeUntil(c,index),giveback=Math.max(0,mfe-r),sig=eventSignals(before,c.side);const flags=[`Evento de gestão: ${label}`,`Estado: ${r>=0?"EM GANHO":"EM PERDA"}`,`R atual: ${r.toFixed(2)}`,`MFE: ${mfe.toFixed(2)}R`,`Devolução desde MFE: ${giveback.toFixed(2)}R`,`MAE: ${mae.toFixed(2)}R`,`Fluxo H1: ${c.h1f??"indefinido"}`,`Score setup: ${c.score}`,`BOS favorável: ${sig.favorableBos?"sim":"não"}`,`BOS contrário: ${sig.adverseBos?"sim":"não"}`,`Deslocamento favorável: ${sig.favorableDisplacement?"sim":"não"}`,`Deslocamento contrário: ${sig.adverseDisplacement?"sim":"não"}`,`Defesa/rejeição favorável: ${sig.defense?"sim":"não"}`,`Rejeição/oposição contrária: ${sig.adverseRejection?"sim":"não"}`,`Defesa em OB/FVG: ${sig.zoneDefense?"sim":"não"}`,`Invalidação forte: ${sig.strongAdverse?"sim":"não"}`,`Novo swing protegido: ${sig.protectedSwing!=null?sig.protectedSwing.toFixed(2):"não"}`];const ctx:AiTradeContext={symbol:"XAUUSD",side:c.side,entry:c.entry,originalStop:c.stop,currentStop:a.currentStop,target1:c.side==="LONG"?c.entry+c.risk*1.5:c.entry-c.risk*1.5,target2:c.take,currentPrice:bar.close,lot:.01,unrealizedR:r,mfeR:mfe,maeR:mae,setupName:"Reversão de Liquidez",reasons:flags,market:{bias:c.h1f,regime:"intraday",structure:flags.join(" | "),factors:flags.map((note,k)=>({label:`Contexto ${k+1}`,score:50,note}))}};return{ctx,sig};}
function settleIfHit(a:Active,from:number,to:number){for(let i=from;i<=to&&i<a.c.path.length;i++){const bar=a.c.path[i],stopHit=a.c.side==="LONG"?bar.low<=a.currentStop:bar.high>=a.currentStop,tpHit=a.c.side==="LONG"?bar.high>=a.c.take:bar.low<=a.c.take;if(stopHit){const r=a.c.side==="LONG"?(a.currentStop-a.c.entry)/a.c.risk:(a.c.entry-a.currentStop)/a.c.risk;a.resultR=a.partialRealized+a.remaining*r;a.done=true;a.cursor=i+1;return true;}if(tpHit){a.resultR=a.partialRealized+a.remaining*2;a.done=true;a.cursor=i+1;return true;}}return false;}
function swingLocksProfit(a:Active,p:number|null,current:number){if(p==null)return false;const min=.05*a.c.risk;return a.c.side==="LONG"?p>a.c.entry+min&&p<current:p<a.c.entry-min&&p>current;}
function findNextManagementEvent(a:Active):ManagementEvent|null{for(let i=Math.max(a.cursor,2);i<a.c.path.length;i++){if(settleIfHit(a,a.cursor,i))return null;const bar=a.c.path[i],r=rAt(bar,a.c.side,a.c.entry,a.c.risk),before=a.c.path.slice(Math.max(0,i-18),i+1),sig=eventSignals(before,a.c.side),mfe=mfeUntil(a.c,i),giveback=Math.max(0,mfe-r);if(sig.strongAdverse){a.cursor=i;return{index:i,label:"INVALIDACAO_FORTE"};}const deterioration=mfe>=1.3&&giveback>=.5&&sig.adverseRejection&&!sig.favorableBos&&!sig.favorableDisplacement;if(deterioration){a.cursor=i;return{index:i,label:"DETERIORACAO_APOS_MFE"};}if(r>0&&sig.strongFavorable&&swingLocksProfit(a,sig.protectedSwing,bar.close)){a.cursor=i;return{index:i,label:"SWING_PROTEGIDO"};}a.cursor=i+1;}return null;}
function structuralStop(a:Active,sig:Signals,currentPrice:number){const p=sig.protectedSwing;if(p==null)return null;const c=a.c,minLock=.05*c.risk;if(c.side==="LONG"){if(p<=Math.max(a.currentStop,c.entry+minLock)||p>=currentPrice)return null;return p;}if(p>=Math.min(a.currentStop,c.entry-minLock)||p<=currentPrice)return null;return p;}
function applyDecision(a:Active,d:AiManagementDecision,ctx:AiTradeContext,sig:Signals,index:number){const r=ctx.unrealizedR;if(d.action==="ENCERRAR"){if(!sig.strongAdverse){a.events.push({r:+r.toFixed(2),action:"MANTER",advice:"ENCERRAR",reason:"Encerramento bloqueado: não há invalidação estrutural forte."});a.cursor=index+1;return;}a.done=true;a.resultR=a.partialRealized+a.remaining*r;a.cursor=index+1;a.events.push({r:+r.toFixed(2),action:"ENCERRAR",reason:d.reason});return;}if(d.action==="PARCIAL"){const giveback=Math.max(0,(ctx.mfeR??r)-r);if((ctx.mfeR??0)<1.3||giveback<.5||!sig.adverseRejection){a.events.push({r:+r.toFixed(2),action:"MANTER",advice:"PARCIAL",reason:"Parcial bloqueada: exige MFE >= 1,3R, devolução >= 0,5R e rejeição/oposição objetiva."});a.cursor=index+1;return;}const pct=Math.max(.1,Math.min(.5,(d.partialPercent??50)/100)),part=a.remaining*pct;a.partialRealized+=part*r;a.remaining-=part;a.cursor=index+1;a.events.push({r:+r.toFixed(2),action:"PARCIAL",percent:Math.round(pct*100),reason:d.reason});return;}if(["PROTEGER","BREAKEVEN","TRAILING"].includes(d.action)){if(r<=0||!sig.strongFavorable){a.events.push({r:+r.toFixed(2),action:"MANTER",advice:d.action,reason:"Proteção bloqueada: falta confirmação estrutural favorável."});a.cursor=index+1;return;}const stop=structuralStop(a,sig,ctx.currentPrice);if(stop==null){a.events.push({r:+r.toFixed(2),action:"MANTER",advice:d.action,reason:"Proteção bloqueada: não existe swing protegido que já trave lucro."});a.cursor=index+1;return;}a.currentStop=stop;a.cursor=index+1;a.events.push({r:+r.toFixed(2),action:d.action,stop:+stop.toFixed(2),reason:`${d.reason} | Stop definido pelo swing estrutural confirmado, sem aumentar risco.`});return;}a.cursor=index+1;a.events.push({r:+r.toFixed(2),action:"MANTER",reason:d.reason});}
function finish(a:Active){if(a.done)return;settleIfHit(a,a.cursor,a.c.path.length-1);if(a.done)return;const last=a.c.path.at(-1);const r=last?rAt(last,a.c.side,a.c.entry,a.c.risk):0;a.resultR=a.partialRealized+a.remaining*Math.max(-1,Math.min(2,r));a.done=true;}

export async function runAiManagementResearch(raw5:Raw[],raw1:Raw[],limit=4,_interventionThreshold=1.5){const cs=buildCandidates(raw5,raw1,limit),active:Active[]=cs.map(c=>({c,currentStop:c.stop,partialRealized:0,remaining:1,done:false,resultR:0,events:[],cursor:0,aiChecks:0}));for(let round=0;round<3;round++){const found=active.map(a=>a.done||a.aiChecks>=3?null:findNextManagementEvent(a)),sel=found.map((e,i)=>e?i:-1).filter(i=>i>=0);if(!sel.length)break;const packs=sel.map(i=>{const e=found[i]!;return{...eventContext(active[i],e.index,e.label),event:e};}),decisions=await manageTradesBatchWithAi(packs.map(p=>p.ctx));for(let k=0;k<sel.length;k++){const i=sel[k],p=packs[k];active[i].aiChecks++;if(!active[i].done)applyDecision(active[i],decisions[k],p.ctx,p.sig,p.event.index);}}
for(const a of active)finish(a);
const rows=active.map(a=>({time:new Date(a.c.time).toISOString(),side:a.c.side,entry:+a.c.entry.toFixed(2),stop:+a.c.stop.toFixed(2),baselineR:+a.c.baselineR.toFixed(2),aiR:+a.resultR.toFixed(2),deltaR:+(a.resultR-a.c.baselineR).toFixed(2),aiChecks:a.aiChecks,events:a.events}));const baselineR=rows.reduce((s,r)=>s+r.baselineR,0),aiR=rows.reduce((s,r)=>s+r.aiR,0);return{sampleSize:rows.length,managementPolicy:"somente-eventos-estruturais",baselineTotalR:+baselineR.toFixed(2),aiManagedTotalR:+aiR.toFixed(2),deltaR:+(aiR-baselineR).toFixed(2),aiCalls:rows.reduce((s,r)=>s+r.aiChecks,0),improved:rows.filter(r=>r.deltaR>0).length,worsened:rows.filter(r=>r.deltaR<0).length,unchanged:rows.filter(r=>r.deltaR===0).length,rows};}