import { manageTradeWithAi, type AiTradeContext, type AiManagementDecision } from "@/lib/ai-manager";

type Raw=any; type Side="LONG"|"SHORT"; type C={time:number;open:number;high:number;low:number;close:number};
type Candidate={side:Side;entry:number;stop:number;take:number;risk:number;time:number;checkpointIndex:number;checkpointR:number;baselineR:number;future:C[];context:AiTradeContext};

function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);if(Number.isFinite(b)&&Number.isFinite(a))return(b+a)/2;if(Number.isFinite(b))return b;if(Number.isFinite(a))return a;return null;}
function norm(r:Raw):C|null{const open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice),s=r?.snapshotTimeUTC??r?.snapshotTime,time=s?Date.parse(String(s).endsWith("Z")?s:`${s}Z`):NaN;if([open,high,low,close].some(x=>x===null)||!Number.isFinite(time))return null;return{time,open:open!,high:high!,low:low!,close:close!};}
function agg(src:C[],m:number){const z=m*60000,out:C[]=[];let k=-1,c:C|null=null;for(const x of src){const b=Math.floor(x.time/z)*z;if(b!==k){if(c)out.push(c);k=b;c={...x,time:b};}else if(c){c.high=Math.max(c.high,x.high);c.low=Math.min(c.low,x.low);c.close=x.close;}}if(c)out.push(c);return out;}
function swings(a:C[],n=2){const hs:number[]=[],ls:number[]=[];for(let i=n;i<a.length-n;i++){let h=true,l=true;for(let j=1;j<=n;j++){if(a[i].high<=a[i-j].high||a[i].high<=a[i+j].high)h=false;if(a[i].low>=a[i-j].low||a[i].low>=a[i+j].low)l=false;}if(h)hs.push(i);if(l)ls.push(i);}return{hs,ls};}
function flow(a:C[]):Side|null{const h=a.slice(-80),s=swings(h);if(s.hs.length<2||s.ls.length<2)return null;const H1=h[s.hs.at(-1)!].high,H0=h[s.hs.at(-2)!].high,L1=h[s.ls.at(-1)!].low,L0=h[s.ls.at(-2)!].low;return H1>H0&&L1>L0?"LONG":H1<H0&&L1<L0?"SHORT":null;}
function fib(a:C[],side:Side,p:number){const x=a.slice(-48);if(x.length<12)return false;const hi=Math.max(...x.map(c=>c.high)),lo=Math.min(...x.map(c=>c.low)),r=hi-lo;if(r<=0)return false;const x61=side==="LONG"?hi-r*.618:lo+r*.618,x786=side==="LONG"?hi-r*.786:lo+r*.786;return p>=Math.min(x61,x786)&&p<=Math.max(x61,x786);}
function fvg(a:C[],side:Side,p:number){for(let i=Math.max(2,a.length-24);i<a.length;i++){const x=a[i-2],z=a[i];if(side==="LONG"&&x.high<z.low&&p>=x.high&&p<=z.low)return true;if(side==="SHORT"&&x.low>z.high&&p<=x.low&&p>=z.high)return true;}return false;}
function displacementAt(a:C[],i:number,side:Side){if(i<10)return false;const c=a[i],prior=a.slice(i-10,i),b=prior.map(x=>Math.abs(x.close-x.open)).sort((x,y)=>x-y),med=b[Math.floor(b.length/2)]||0,body=Math.abs(c.close-c.open),rng=c.high-c.low||1,dir=side==="LONG"?c.close>c.open:c.close<c.open;return dir&&body>med*1.5&&body/rng>.58;}
function displacement(a:C[],side:Side){return a.length>10&&displacementAt(a,a.length-1,side);}
function obValidated(a:C[],side:Side,p:number){for(let i=a.length-5;i>=Math.max(2,a.length-30);i--){const c=a[i];if(side==="LONG"&&c.close<c.open){for(let j=i+1;j<=Math.min(i+4,a.length-1);j++)if(displacementAt(a,j,"LONG")&&a[j].close>c.high&&p>=c.low&&p<=c.high)return true;}if(side==="SHORT"&&c.close>c.open){for(let j=i+1;j<=Math.min(i+4,a.length-1);j++)if(displacementAt(a,j,"SHORT")&&a[j].close<c.low&&p>=c.low&&p<=c.high)return true;}}return false;}
function sweepLocal(a:C[],side:Side,n=10){if(a.length<n+1)return false;const s=a.at(-1)!,q=a.slice(-n-1,-1),lo=Math.min(...q.map(x=>x.low)),hi=Math.max(...q.map(x=>x.high));return side==="LONG"?s.low<lo&&s.close>lo:s.high>hi&&s.close<hi;}
function candle(a:C[],side:Side){if(a.length<2)return false;const c=a.at(-1)!,p=a.at(-2)!,body=Math.abs(c.close-c.open),rng=c.high-c.low||1;const engulf=side==="LONG"?c.close>c.open&&p.close<p.open&&c.close>=p.open&&c.open<=p.close:c.close<c.open&&p.close>p.open&&c.close<=p.open&&c.open>=p.close;const pin=side==="LONG"?(Math.min(c.open,c.close)-c.low)>body*1.6&&body/rng<.5:(c.high-Math.max(c.open,c.close))>body*1.6&&body/rng<.5;return engulf||pin;}
function bos(a:C[],side:Side,n=5){if(a.length<n+1)return false;const c=a.at(-1)!,q=a.slice(-n-1,-1);return side==="LONG"?c.close>Math.max(...q.map(x=>x.high)):c.close<Math.min(...q.map(x=>x.low));}
function m1ok(a:C[],side:Side,t:number){if(a.length<8||!a.at(-1)||a.at(-1)!.time<t-120000)return false;return bos(a,side,4)||candle(a,side)||sweepLocal(a,side,7)||displacement(a,side);}
function inWindow(t:number){const d=new Date(t),m=d.getUTCHours()*60+d.getUTCMinutes();return m<=1110;}
function dayKey(t:number){const d=new Date(t);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate());}
function prevDayLevels(all:C[],i:number){const today=dayKey(all[i].time);let hi=-Infinity,lo=Infinity,found=false,prev:number|null=null;for(let j=i-1;j>=0;j--){const dk=dayKey(all[j].time);if(dk===today)continue;if(!found){found=true;prev=dk;}else if(dk!==prev)break;hi=Math.max(hi,all[j].high);lo=Math.min(lo,all[j].low);}return found?{hi,lo}:null;}
function sessionLevels(all:C[],i:number){const today=dayKey(all[i].time),asiaEnd=today+6*3600000;let asiaHi=-Infinity,asiaLo=Infinity,midOpen:number|null=null;for(let j=i;j>=0;j--){if(dayKey(all[j].time)!==today)break;if(all[j].time<asiaEnd){asiaHi=Math.max(asiaHi,all[j].high);asiaLo=Math.min(asiaLo,all[j].low);}midOpen=all[j].open;}return{asiaHi,asiaLo,midOpen};}
function sweepLevel(c:C,side:Side,levels:number[]){return levels.some(l=>Number.isFinite(l)&&(side==="LONG"?c.low<l&&c.close>l:c.high>l&&c.close<l));}
function rAt(c:C,side:Side,en:number,risk:number){return side==="LONG"?(c.close-en)/risk:(en-c.close)/risk;}
function outcome(path:C[],side:Side,en:number,stop:number,take:number,start=0){for(let j=start;j<path.length;j++){const c=path[j],sh=side==="LONG"?c.low<=stop:c.high>=stop,th=side==="LONG"?c.high>=take:c.low<=take;if(sh)return -Math.abs(en-stop)/Math.abs(en-stop);if(th)return Math.abs(take-en)/Math.abs(en-stop);}const c=path.at(-1);if(!c)return 0;return Math.max(-1,Math.min(2,side==="LONG"?(c.close-en)/Math.abs(en-stop):(en-c.close)/Math.abs(en-stop)));}

function buildCandidates(raw5:Raw[],raw1:Raw[],limit:number){const m5=raw5.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m1=raw1.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m15=agg(m5,15),h1=agg(m5,60);const out:Candidate[]=[];let blocked=-1,p15=-1,p1=-1,pm1=-1;for(let i=120;i<m5.length-50&&out.length<limit;i++){const s=m5[i],ct=s.time+300000;while(p15+1<m15.length&&m15[p15+1].time<=ct-900000)p15++;while(p1+1<h1.length&&h1[p1+1].time<=ct-3600000)p1++;while(pm1+1<m1.length&&m1[pm1+1].time<=s.time)pm1++;if(i<=blocked||p15<40||p1<25||pm1<8||!inWindow(s.time))continue;const a5=m5.slice(Math.max(0,i-120),i+1),a15=m15.slice(Math.max(0,p15-100),p15+1),a1=h1.slice(Math.max(0,p1-100),p1+1),aM1=m1.slice(Math.max(0,pm1-25),pm1+1),h1f=flow(a1),pd=prevDayLevels(m5,i),sess=sessionLevels(m5,i);for(const side of ["LONG","SHORT"] as Side[]){const levels=side==="LONG"?[pd?.lo??NaN,sess.asiaLo,sess.midOpen??NaN]:[pd?.hi??NaN,sess.asiaHi,sess.midOpen??NaN];const majorSweep=sweepLevel(s,side,levels);let score=0;if(majorSweep)score+=28;if(sweepLocal(a5,side,8))score+=10;if(displacement(a5,side))score+=16;if(bos(a5,side))score+=16;if(obValidated(a5,side,s.close)||obValidated(a15,side,s.close))score+=12;if(fvg(a5,side,s.close)||fvg(a15,side,s.close))score+=10;if(candle(a5,side))score+=8;if(h1f&&h1f!==side)score+=6;if(fib(a5,side,s.close))score+=10;if(score<58||!m1ok(aM1,side,s.time))continue;const en=m5[i+1].open,stop=side==="LONG"?Math.min(...a5.slice(-10).map(c=>c.low)):Math.max(...a5.slice(-10).map(c=>c.high)),risk=Math.abs(en-stop);if(risk<=0||risk/en>.008)continue;const take=side==="LONG"?en+risk*2:en-risk*2,path=m5.slice(i+1,Math.min(i+49,m5.length));let checkpointIndex=Math.min(5,path.length-1),checkpointR=0;for(let j=1;j<path.length;j++){const r=rAt(path[j],side,en,risk);if(r>=.6||r<=-.5){checkpointIndex=j;checkpointR=r;break}if(j===checkpointIndex)checkpointR=r;}const baselineR=outcome(path,side,en,stop,take,0),cp=path[checkpointIndex],before=path.slice(Math.max(0,checkpointIndex-12),checkpointIndex+1);const flags=[`Fluxo H1: ${h1f??"indefinido"}`,`Score setup: ${score}`,`Sweep relevante: ${majorSweep?"sim":"não"}`,`BOS M5: ${bos(before,side)?"sim":"não"}`,`Deslocamento M5: ${displacement(before,side)?"sim":"não"}`,`FVG/OB próximo: ${fvg(before,side,cp.close)||obValidated(before,side,cp.close)?"sim":"não"}`];const ctx:AiTradeContext={symbol:"XAUUSD",side,entry:en,originalStop:stop,currentStop:stop,target1:side==="LONG"?en+risk*1.5:en-risk*1.5,target2:take,currentPrice:cp.close,lot:.01,unrealizedR:checkpointR,mfeR:null,maeR:null,setupName:"Reversão de Liquidez",reasons:flags,market:{bias:h1f,regime:"intraday",structure:flags.join(" | "),factors:flags.map((note,k)=>({label:`Contexto ${k+1}`,score:50,note}))}};out.push({side,entry:en,stop,take,risk,time:s.time,checkpointIndex,checkpointR,baselineR,future:path.slice(checkpointIndex),context:ctx});blocked=i+Math.max(1,checkpointIndex);break;}}
return out;}

function managedR(c:Candidate,d:AiManagementDecision){if(d.action==="ENCERRAR")return c.checkpointR;if(d.action==="PARCIAL"){const p=(d.partialPercent??50)/100,rest=outcome(c.future,c.side,c.entry,c.stop,c.take,0);return p*c.checkpointR+(1-p)*rest;}if(["PROTEGER","BREAKEVEN","TRAILING"].includes(d.action)&&d.suggestedStop!=null){return outcome(c.future,c.side,c.entry,d.suggestedStop,c.take,0);}return c.baselineR;}

export async function runAiManagementResearch(raw5:Raw[],raw1:Raw[],limit=8){const cs=buildCandidates(raw5,raw1,limit),rows=[] as any[];for(const c of cs){const decision=await manageTradeWithAi(c.context),aiR=managedR(c,decision);rows.push({time:new Date(c.time).toISOString(),side:c.side,entry:+c.entry.toFixed(2),stop:+c.stop.toFixed(2),checkpointR:+c.checkpointR.toFixed(2),baselineR:+c.baselineR.toFixed(2),aiR:+aiR.toFixed(2),deltaR:+(aiR-c.baselineR).toFixed(2),action:decision.action,confidence:decision.confidence,provider:decision.provider,reason:decision.reason});}
const baselineR=rows.reduce((s,r)=>s+r.baselineR,0),aiR=rows.reduce((s,r)=>s+r.aiR,0);return{sampleSize:rows.length,baselineTotalR:+baselineR.toFixed(2),aiManagedTotalR:+aiR.toFixed(2),deltaR:+(aiR-baselineR).toFixed(2),improved:rows.filter(r=>r.deltaR>0).length,worsened:rows.filter(r=>r.deltaR<0).length,unchanged:rows.filter(r=>r.deltaR===0).length,provider:rows.every(r=>r.provider==="groq")?"groq":"mixed/fallback",rows};}
