type Raw=any;type Side=1|-1;
type C={time:number;open:number;high:number;low:number;close:number;volume:number};
type Trade={entryTime:number;exitTime:number;side:Side;setup:"FVG"|"NY";entry:number;stop0:number;target:number;risk:number;r:number;reason:string};

function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);return Number.isFinite(b)&&Number.isFinite(a)?(b+a)/2:Number.isFinite(b)?b:Number.isFinite(a)?a:NaN}
function norm(r:Raw):C|null{const s=String(r?.snapshotTimeUTC??r?.snapshotTime??r?.time??""),time=Date.parse(s.endsWith("Z")?s:s+"Z"),open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice),volume=Number(r?.lastTradedVolume??r?.volume??0);return[time,open,high,low,close].every(Number.isFinite)?{time,open,high,low,close,volume:Number.isFinite(volume)?volume:0}:null}
function prep(raw:Raw[]){return raw.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time)}
function ema(vals:number[],n:number){const out=new Array(vals.length).fill(NaN),k=2/(n+1);let e=NaN;for(let i=0;i<vals.length;i++){e=Number.isFinite(e)?vals[i]*k+e*(1-k):vals[i];out[i]=e}return out}
function rollingMean(a:number[],n:number){const o=new Array(a.length).fill(NaN);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=n)s-=a[i-n];if(i>=n-1)o[i]=s/n}return o}
function rollingMedian(a:number[],n:number,minp:number){const o=new Array(a.length).fill(NaN);for(let i=minp-1;i<a.length;i++){const lo=Math.max(0,i-n+1),z=a.slice(lo,i+1).filter(Number.isFinite).sort((x,y)=>x-y);if(z.length<minp)continue;const m=Math.floor(z.length/2);o[i]=z.length%2?z[m]:(z[m-1]+z[m])/2}return o}
function tr(a:C[]){return a.map((c,i)=>i?Math.max(c.high-c.low,Math.abs(c.high-a[i-1].close),Math.abs(c.low-a[i-1].close)):c.high-c.low)}
function rsi(cl:number[],n=14){const g=new Array(cl.length).fill(0),l=new Array(cl.length).fill(0);for(let i=1;i<cl.length;i++){const d=cl[i]-cl[i-1];g[i]=Math.max(d,0);l[i]=Math.max(-d,0)}const gm=rollingMean(g,n),lm=rollingMean(l,n),o=new Array(cl.length).fill(NaN);for(let i=0;i<cl.length;i++){if(!Number.isFinite(gm[i])||!Number.isFinite(lm[i]))continue;o[i]=lm[i]===0?100:100-100/(1+gm[i]/lm[i])}return o}
function dstStartUtc(y:number){const d=new Date(Date.UTC(y,2,1));const first=(7-d.getUTCDay())%7+1,second=first+7;return Date.UTC(y,2,second,7)}
function dstEndUtc(y:number){const d=new Date(Date.UTC(y,10,1));const first=(7-d.getUTCDay())%7+1;return Date.UTC(y,10,first,6)}
function nyLocal(t:number){const y=new Date(t).getUTCFullYear(),off=t>=dstStartUtc(y)&&t<dstEndUtc(y)?-4:-5,d=new Date(t+off*3600000);return{date:`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`,minute:d.getUTCHours()*60+d.getUTCMinutes()}}
function dayUtc(t:number){const d=new Date(t);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())}
function dailySide(raw:Raw[]){const a=prep(raw),cl=a.map(x=>x.close),e20=ema(cl,20),e100=ema(cl,100),rows:{day:number;side:number}[]=[];const rawSide=new Array(a.length).fill(0);for(let i=252;i<a.length;i++){const mom=cl[i]/cl[i-252]-1,trend=e20[i]>e100[i]?1:e20[i]<e100[i]?-1:0;rawSide[i]=trend>0&&mom>0?1:trend<0&&mom<0?-1:0}for(let i=1;i<a.length;i++)rows.push({day:dayUtc(a[i].time),side:rawSide[i-1]});return rows}
function mapDailySide(a:C[],rows:{day:number;side:number}[]){const out=new Array(a.length).fill(0);let j=0,last=0;for(let i=0;i<a.length;i++){const d=dayUtc(a[i].time);while(j<rows.length&&rows[j].day<=d){last=rows[j].side;j++}out[i]=last}return out}
function h4Bias(a:C[]){const groups=new Map<number,C[]>();for(const c of a){const k=Math.floor(c.time/(4*3600000))*4*3600000,z=groups.get(k)||[];z.push(c);groups.set(k,z)}const h=[...groups.entries()].sort((x,y)=>x[0]-y[0]).map(([k,z])=>({end:k+4*3600000,close:z[z.length-1].close})),e=ema(h.map(x=>x.close),50),out=new Array(a.length).fill(0);let j=0,last=0;for(let i=0;i<a.length;i++){const closedAt=a[i].time+15*60000;while(j<h.length&&h[j].end<=closedAt){if(j>=49)last=h[j].close>e[j]?1:h[j].close<e[j]?-1:0;j++}out[i]=last}return out}
function features(a:C[]){const cl=a.map(x=>x.close),T=tr(a),atr14=rollingMean(T,14),atr56=rollingMean(T,56),med=rollingMedian(atr56,2000,200),volma=rollingMean(a.map(x=>x.volume),20),R=rsi(cl,14),h4=h4Bias(a),vwap=new Array(a.length).fill(NaN),swingLo=new Array(a.length).fill(NaN),swingHi=new Array(a.length).fill(NaN);let pv=0,v=0,lastDay="",lo=NaN,hi=NaN;
  for(let i=0;i<a.length;i++){const n=nyLocal(a[i].time);if(n.date!==lastDay){lastDay=n.date;pv=0;v=0}const tp=(a[i].high+a[i].low+a[i].close)/3;pv+=tp*a[i].volume;v+=a[i].volume;vwap[i]=v>0?pv/v:NaN;if(i>=10){const c=i-5,w=a.slice(c-5,c+6),lh=w.map(x=>x.low),hh=w.map(x=>x.high);if(a[c].low===Math.min(...lh)&&lh.filter(x=>x===a[c].low).length===1)lo=a[c].low;if(a[c].high===Math.max(...hh)&&hh.filter(x=>x===a[c].high).length===1)hi=a[c].high}swingLo[i]=lo;swingHi[i]=hi}
  return{atr14,atr56,med,volma,R,h4,vwap,swingLo,swingHi}
}
function stopFor(side:Side,entry:number,atr:number,swing:number){const atrStop=entry-side*atr*1.5;if(!Number.isFinite(swing))return atrStop;const dist=side===1?entry-swing:swing-entry;if(dist<atr*.5||dist>atr*4)return atrStop;return side===1?swing-atr*.1:swing+atr*.1}
function metrics(ts:Trade[],spanDays:number){const R=ts.map(x=>x.r),n=R.length,w=R.filter(x=>x>0).length,net=R.reduce((s,x)=>s+x,0),gp=R.filter(x=>x>0).reduce((s,x)=>s+x,0),gl=-R.filter(x=>x<0).reduce((s,x)=>s+x,0);let eq=0,pk=0,dd=0;for(const x of R){eq+=x;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq)}const months=new Map<string,number>();for(const t of ts){const d=new Date(t.exitTime),k=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;months.set(k,(months.get(k)||0)+t.r)}const mv=[...months.values()];return{trades:n,winRate:+(n?w/n*100:0).toFixed(1),netR:+net.toFixed(2),avgR:+(n?net/n:0).toFixed(3),profitFactor:+(gl?gp/gl:gp>0?99:0).toFixed(2),maxDrawdownR:+dd.toFixed(2),tradesPerDay:+(n/Math.max(1,spanDays*5/7)).toFixed(2),positiveMonths:+(mv.length?mv.filter(x=>x>0).length/mv.length:0).toFixed(2)}}
function run(a:C[],dside:number[],gate:boolean,costMult:number){const f=features(a),out:Trade[]=[];let open:any=null,pending:any=null,tradesToday=0,curDay="",nyState=new Map<string,{bull:boolean;bear:boolean}>(),first8=new Map<string,C[]>();
  for(let i=0;i<a.length;i++){const c=a[i],nl=nyLocal(c.time);if(nl.date!==curDay){curDay=nl.date;tradesToday=0}if(nl.minute===480||nl.minute===495){const z=first8.get(nl.date)||[];z.push(c);first8.set(nl.date,z);if(z.length>=2)nyState.set(nl.date,{bull:z[0].close>z[0].open&&z[1].close>z[1].open,bear:z[0].close<z[0].open&&z[1].close<z[1].open})}
    if(pending&&!open){const adj=.25*costMult,fill=pending.side===1?c.open+adj:c.open-adj,risk=Math.abs(fill-pending.stop);if(risk>0)open={...pending,entry:fill,risk,be:false,stopLive:pending.stop};pending=null;tradesToday++}
    if(open){const adj=.25*costMult;let exit:number|null=null,reason="";if(open.side===1){if(c.low<=open.stopLive){exit=open.stopLive-adj;reason=open.be?"BE":"STOP"}else if(c.high>=open.target){exit=open.target-adj;reason="TARGET"}}else{if(c.high>=open.stopLive){exit=open.stopLive+adj;reason=open.be?"BE":"STOP"}else if(c.low<=open.target){exit=open.target+adj;reason="TARGET"}}if(exit===null&&!open.be){const fav=open.side===1?c.high-open.entry:open.entry-c.low;if(fav>=1.5*open.risk){open.stopLive=open.entry;open.be=true}}if(exit!==null){const r=open.side===1?(exit-open.entry)/open.risk:(open.entry-exit)/open.risk;out.push({entryTime:open.entryTime,exitTime:c.time,side:open.side,setup:open.setup,entry:open.entry,stop0:open.stop,target:open.target,risk:open.risk,r:+r.toFixed(4),reason});open=null}}
    if(open||pending||i+1>=a.length||tradesToday>=3||!Number.isFinite(f.atr14[i])||f.h4[i]===0||dside[i]===0)continue;
    if(gate&&(!Number.isFinite(f.atr56[i])||!Number.isFinite(f.med[i])||f.atr56[i]<f.med[i]))continue;
    const range=c.high-c.low||1,gapBull=i>=2?c.low-a[i-2].high:-1,gapBear=i>=2?a[i-2].low-c.high:-1,fvgBull=gapBull>0&&gapBull/f.atr14[i]>.25,fvgBear=gapBear>0&&gapBear/f.atr14[i]>.25,volOk=a[i].volume>0&&Number.isFinite(f.volma[i])&&a[i].volume>f.volma[i]*1.2,sess=(nl.minute>=300&&nl.minute<390)||(nl.minute>=495&&nl.minute<570)||(nl.minute>=570&&nl.minute<630),ns=nyState.get(nl.date),nyLong=!!ns?.bull&&f.R[i]>45&&f.R[i]<75&&c.close>f.vwap[i]&&f.h4[i]===1,nyShort=!!ns?.bear&&f.R[i]>25&&f.R[i]<55&&c.close<f.vwap[i]&&f.h4[i]===-1,regLong=sess&&fvgBull&&volOk&&f.h4[i]===1,regShort=sess&&fvgBear&&volOk&&f.h4[i]===-1;let side:Side|null=null,setup:"FVG"|"NY"="FVG";if(nyLong||regLong){side=1;setup=nyLong?"NY":"FVG"}else if(nyShort||regShort){side=-1;setup=nyShort?"NY":"FVG"}if(!side||dside[i]!==side)continue;const sigEntry=c.close,stop=stopFor(side,sigEntry,f.atr14[i],side===1?f.swingLo[i]:f.swingHi[i]),rr=setup==="NY"?3:2.5,target=sigEntry+side*Math.abs(sigEntry-stop)*rr;pending={side,setup,stop,target,entryTime:a[i+1].time}
  }return out}
export function runAtrStackLab(raw15:Raw[],rawDay:Raw[]){const a=prep(raw15),d=dailySide(rawDay);if(a.length<3000||d.length<260)return{status:"insufficient_data",m15:a.length,daily:d.length};const ds=mapDailySide(a,d),span=(a[a.length-1].time-a[0].time)/86400000,volumePct=+(a.filter(x=>x.volume>0).length/a.length*100).toFixed(1),variants:any={};for(const gated of [false,true])for(const cost of [1,3,5]){const k=(gated?"ATR_GATE":"BASE")+"_"+cost+"X",ts=run(a,ds,gated,cost);variants[k]={...metrics(ts,span),setups:{FVG:ts.filter(x=>x.setup==="FVG").length,NY:ts.filter(x=>x.setup==="NY").length},longs:ts.filter(x=>x.side===1).length,shorts:ts.filter(x=>x.side===-1).length}}
  const g=variants.ATR_GATE_1X,b=variants.BASE_1X,g5=variants.ATR_GATE_5X;const pass=g.trades>=25&&g.avgR>=.05&&g.profitFactor>=1.15&&g.positiveMonths>=.6&&g5.avgR>0&&g.avgR>b.avgR;
  return{status:"ok",model:"GOLD_RESEARCH_ATR_STACK_REPLICATION_V1",m15Candles:a.length,dailyCandles:d.length,volumeAvailablePct:volumePct,from:new Date(a[0].time).toISOString(),to:new Date(a[a.length-1].time).toISOString(),rules:{timeframe:"M15",entries:"FVG + NY Opening; displacement OFF",htf:"closed H4 EMA50",dailyDirection:"EMA20/100 + 252-session momentum, lagged one daily bar",volatilityGate:"ATR56 >= rolling median 2000 bars (min 200)",risk:"swing/1.5 ATR stop; FVG 2.5R; NY 3R; BE at 1.5R; max 3/day",cost:"1x = spread 0.30 + slippage 0.10 per fill model => 0.25 point adverse each fill; 3x/5x scale fill cost"},variants,pass,verdict:pass?"CANDIDATE_FOR_FORWARD_ONLY":"REJECT_OR_KEEP_IN_LAB",warning:"Replication on Capital.com mid candles. No real-money use; promotion requires repeated older-window validation and LIVE shadow."}}
