type Raw=any;type Side="LONG"|"SHORT";
export type C={time:number;open:number;high:number;low:number;close:number};
export type T={time:number;side:Side;entry:number;stop:number;risk:number;netR:number;grossR:number;exitTime:number;family:string};
export type Metrics={trades:number;winRate:number;netR:number;avgR:number;profitFactor:number;maxDrawdownR:number;tradesPerDay:number};
export function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);return Number.isFinite(b)&&Number.isFinite(a)?(b+a)/2:Number.isFinite(b)?b:Number.isFinite(a)?a:NaN}
export function norm(r:Raw):C|null{const s=String(r?.snapshotTimeUTC??r?.snapshotTime??r?.time??""),time=Date.parse(s.endsWith("Z")?s:s+"Z"),open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice);return[time,open,high,low,close].every(Number.isFinite)?{time,open,high,low,close}:null}
export function atr(a:C[],i:number,n=24){let s=0,k=0;for(let j=Math.max(1,i-n+1);j<=i;j++){const x=a[j],p=a[j-1];s+=Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close));k++}return k?s/k:0}
export function inWindow(t:number){const d=new Date(t),m=d.getUTCHours()*60+d.getUTCMinutes();return m>=0&&m<=1110}
export function day(t:number){const d=new Date(t);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())}
export function simulate(a:C[],start:number,side:Side,entry:number,stop:number,targetR:number,maxBars:number,cost=.5){const risk=Math.abs(entry-stop);if(!risk)return null;const tp=side==="LONG"?entry+risk*targetR:entry-risk*targetR;let gross=0,exit=a[Math.min(a.length-1,start+maxBars-1)]?.time??a[start].time;for(let j=start;j<Math.min(a.length,start+maxBars);j++){const c=a[j],sl=side==="LONG"?c.low<=stop:c.high>=stop,hit=side==="LONG"?c.high>=tp:c.low<=tp;if(sl){gross=-1;exit=c.time;break}if(hit){gross=targetR;exit=c.time;break}if(j===Math.min(a.length-1,start+maxBars-1)){gross=side==="LONG"?(c.close-entry)/risk:(entry-c.close)/risk;gross=Math.max(-1,Math.min(targetR,gross))}}return{grossR:gross,netR:gross-cost/risk,exitTime:exit,risk}}
export function push(out:T[],a:C[],i:number,side:Side,stop:number,targetR:number,maxBars:number,family:string){if(i+1>=a.length)return false;const entry=a[i+1].open,risk=Math.abs(entry-stop),rp=risk/entry;if(risk<=0||rp>.0035||rp<.00035)return false;const s=simulate(a,i+1,side,entry,stop,targetR,maxBars);if(!s)return false;out.push({time:a[i].time,side,entry,stop,risk,netR:s.netR,grossR:s.grossR,exitTime:s.exitTime,family});return true}
export function metrics(ts:T[],spanDays:number):Metrics{const n=ts.length,w=ts.filter(x=>x.netR>0).length,net=ts.reduce((s,x)=>s+x.netR,0),gp=ts.filter(x=>x.netR>0).reduce((s,x)=>s+x.netR,0),gl=-ts.filter(x=>x.netR<0).reduce((s,x)=>s+x.netR,0);let eq=0,pk=0,dd=0;for(const x of ts){eq+=x.netR;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq)}return{trades:n,winRate:+(n?w/n*100:0).toFixed(1),netR:+net.toFixed(2),avgR:+(n?net/n:0).toFixed(3),profitFactor:+(gl?gp/gl:gp>0?99:0).toFixed(2),maxDrawdownR:+dd.toFixed(2),tradesPerDay:+(n/Math.max(1,spanDays*5/7)).toFixed(2)}}
export function blockMetrics(ts:T[],start:number,end:number,count=3){const w=(end-start)/count;return Array.from({length:count},(_,b)=>{const lo=start+b*w,hi=b===count-1?end+1:start+(b+1)*w;return metrics(ts.filter(x=>x.time>=lo&&x.time<hi),(hi-lo)/86400000)})}
export function prep(raw:Raw[]){return raw.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time)}
export function buildLevels(a:C[]){const pd=new Map<number,{hi:number;lo:number}>(),asia=new Map<number,{hi:number;lo:number}>(),days=new Map<number,C[]>();for(const c of a){const d=day(c.time),x=days.get(d)||[];x.push(c);days.set(d,x)}const keys=[...days.keys()].sort((x,y)=>x-y);for(let k=0;k<keys.length;k++){const d=keys[k],cs=days.get(d)!;if(k){const p=days.get(keys[k-1])!;pd.set(d,{hi:Math.max(...p.map(x=>x.high)),lo:Math.min(...p.map(x=>x.low))})}const z=cs.filter(x=>new Date(x.time).getUTCHours()<6);if(z.length)asia.set(d,{hi:Math.max(...z.map(x=>x.high)),lo:Math.min(...z.map(x=>x.low))})}return{pd,asia}}
