
type Raw=any;
type SessionName="ASIA"|"EUROPE"|"US";
type C={time:number;open:number;high:number;low:number;close:number};
type S={date:string;session:SessionName;start:number;end:number;open30:number;open60:number;range30:number;close30:number;close60:number};
type T={time:number;date:string;session:SessionName;side:-1|1;gross:number;net:number};

function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);if(Number.isFinite(b)&&Number.isFinite(a))return(b+a)/2;if(Number.isFinite(b))return b;if(Number.isFinite(a))return a;return NaN}
function norm(r:Raw):C|null{const s=String(r?.snapshotTimeUTC??r?.snapshotTime??r?.time??""),time=Date.parse(s.endsWith("Z")?s:s+"Z"),open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice);return[time,open,high,low,close].every(Number.isFinite)?{time,open,high,low,close}:null}
function prep(raw:Raw[]){return raw.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time)}
function dateKey(t:number){const d=new Date(t);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`}
function sessionOf(t:number):SessionName|null{const d=new Date(t),m=d.getUTCHours()*60+d.getUTCMinutes();if(m>=0&&m<480)return"ASIA";if(m>=480&&m<870)return"EUROPE";if(m>=870&&m<1440)return"US";return null}
function sessions(a:C[]):S[]{const g=new Map<string,C[]>();for(const c of a){const s=sessionOf(c.time);if(!s)continue;const k=dateKey(c.time)+"|"+s,z=g.get(k)||[];z.push(c);g.set(k,z)}const out:S[]=[];for(const[k,z0]of g){const z=[...z0].sort((x,y)=>x.time-y.time);if(z.length<8)continue;const[date,session]=k.split("|") as [string,SessionName];const f2=z.slice(0,2),f4=z.slice(0,4),l2=z.slice(-2),l4=z.slice(-4),o=z[0].open;if(!o)continue;out.push({date,session,start:z[0].time,end:z[z.length-1].time+900000,open30:f2[f2.length-1].close/o-1,open60:f4[f4.length-1].close/o-1,range30:(Math.max(...f2.map(x=>x.high))-Math.min(...f2.map(x=>x.low)))/o,close30:l2[l2.length-1].close/l2[0].open-1,close60:l4[l4.length-1].close/l4[0].open-1})}return out.sort((a,b)=>a.start-b.start)}
function median(xs:number[]){if(!xs.length)return NaN;const z=[...xs].sort((a,b)=>a-b),m=Math.floor(z.length/2);return z.length%2?z[m]:(z[m-1]+z[m])/2}
function metrics(ts:T[],spanDays:number){const r=ts.map(x=>x.net),n=r.length,w=r.filter(x=>x>0),loss=r.filter(x=>x<=0),gp=w.reduce((s,x)=>s+x,0),gl=-loss.reduce((s,x)=>s+x,0);let eq=1,pk=1,dd=0;for(const x of r){eq*=1+x;pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}const daily=new Map<string,number>();for(const t of ts)daily.set(t.date,(daily.get(t.date)||0)+t.net);const dr=[...daily.values()],mu=dr.length?dr.reduce((s,x)=>s+x,0)/dr.length:0,vr=dr.length>1?dr.reduce((s,x)=>s+(x-mu)**2,0)/(dr.length-1):0,sd=Math.sqrt(vr);const months=new Map<string,number>();for(const t of ts){const m=t.date.slice(0,7);months.set(m,(months.get(m)||0)+t.net)}const mv=[...months.values()];return{trades:n,winRate:+(n?w.length/n*100:0).toFixed(1),totalReturnPct:+((eq-1)*100).toFixed(2),avgTradeBps:+(n?r.reduce((s,x)=>s+x,0)/n*10000:0).toFixed(2),profitFactor:+(gl?gp/gl:gp>0?99:0).toFixed(2),maxDrawdownPct:+(dd*100).toFixed(2),dailySharpe:+(sd?mu/sd*Math.sqrt(252):0).toFixed(2),tradesPerDay:+(n/Math.max(1,spanDays*5/7)).toFixed(2),positiveMonths:+(mv.length?mv.filter(x=>x>0).length/mv.length:0).toFixed(2),asia:ts.filter(x=>x.session==="ASIA").length,europe:ts.filter(x=>x.session==="EUROPE").length,us:ts.filter(x=>x.session==="US").length}}
type Spec={id:string;open:"open30"|"open60";close:"close30"|"close60";volGate:boolean};
function build(ss:S[],spec:Spec,cost:number){const out:T[]=[],hist:Record<SessionName,number[]>={ASIA:[],EUROPE:[],US:[]};for(const x of ss){const h=hist[x.session],med=h.length>=30?median(h.slice(-60)):NaN,volOk=!spec.volGate||(Number.isFinite(med)&&x.range30>=med),sig=x[spec.open];if(volOk&&sig!==0&&Number.isFinite(sig)){const side:(-1|1)=sig>0?1:-1,gross=x[spec.close]*side;out.push({time:x.end,date:x.date,session:x.session,side,gross,net:gross-cost})}h.push(x.range30)}return out}
export function runIntradayCloseMomentumLab(raw:Raw[],evalDays=180){const a=prep(raw),ss=sessions(a);if(ss.length<200)return{status:"insufficient_data",candles:a.length,sessions:ss.length};const last=ss[ss.length-1].end,evalStart=last-evalDays*86400000,evalSs=ss.filter(x=>x.end>=evalStart),span=(last-evalStart)/86400000;const specs:Spec[]=[{id:"O30_C30",open:"open30",close:"close30",volGate:false},{id:"O30_C30_VOLMED",open:"open30",close:"close30",volGate:true},{id:"O60_C30_VOLMED",open:"open60",close:"close30",volGate:true},{id:"O30_C60_VOLMED",open:"open30",close:"close60",volGate:true}];const variants:any={};for(const s of specs){variants[s.id]={COST_2BPS:metrics(build(evalSs,s,.0002),span),COST_4BPS:metrics(build(evalSs,s,.0004),span),COST_6BPS:metrics(build(evalSs,s,.0006),span)}}const ranking=specs.map(s=>({id:s.id,...variants[s.id].COST_2BPS})).sort((x,y)=>y.dailySharpe-x.dailySharpe);return{status:"ok",model:"INTRADAY_OPEN_TO_CLOSE_MOMENTUM_V1",candles:a.length,sessions:ss.length,from:new Date(a[0].time).toISOString(),evaluationFrom:new Date(evalStart).toISOString(),to:new Date(a[a.length-1].time).toISOString(),rules:{sessions:"Asia 00:00-08:00 UTC; Europe 08:00-14:30 UTC; US 14:30-24:00 UTC",signal:"sign of first 30m or 60m session return",trade:"hold only final 30m or 60m of same session",volGate:"current first-30m range >= causal rolling median of prior up to 60 same-session openings; minimum 30 observations",costs:"2/4/6 bps round-trip deducted from each trade"},variants,ranking,warning:"Research only. Development windows 2019-2026 may inform selection; any candidate must be frozen before testing untouched older HistData years."}}
