import type { HistCandle } from "@/lib/histdata";
type Raw=any; type Side=1|-1;
type C={time:number;open:number;high:number;low:number;close:number};
type T={time:number;date:string;side:Side;entry:number;exit:number;range:number;grossRtn:number;netRtn:number;costPoints:number};
function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);if(Number.isFinite(b)&&Number.isFinite(a))return(b+a)/2;if(Number.isFinite(b))return b;if(Number.isFinite(a))return a;return NaN}
function norm(r:Raw):C|null{const s=String(r?.snapshotTimeUTC??r?.snapshotTime??""),time=Date.parse(s),open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice);return[time,open,high,low,close].every(Number.isFinite)?{time,open,high,low,close}:null}
function dstStart(y:number){const d=new Date(Date.UTC(y,2,1)),f=(7-d.getUTCDay())%7+1;return Date.UTC(y,2,f+7,7)}
function dstEnd(y:number){const d=new Date(Date.UTC(y,10,1)),f=(7-d.getUTCDay())%7+1;return Date.UTC(y,10,f,6)}
function ny(t:number){const y=new Date(t).getUTCFullYear(),off=t>=dstStart(y)&&t<dstEnd(y)?-4:-5,d=new Date(t+off*3600000);return{date:`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`,m:d.getUTCHours()*60+d.getUTCMinutes()}}
function median(xs:number[]){if(!xs.length)return NaN;const z=[...xs].sort((a,b)=>a-b),m=Math.floor(z.length/2);return z.length%2?z[m]:(z[m-1]+z[m])/2}
function metrics(ts:T[]){const r=ts.map(x=>x.netRtn),n=r.length,w=r.filter(x=>x>0),loss=r.filter(x=>x<=0),gp=w.reduce((s,x)=>s+x,0),gl=-loss.reduce((s,x)=>s+x,0);let eq=1,pk=1,dd=0;for(const x of r){eq*=1+x;pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}const daily=new Map<string,number>();for(const t of ts)daily.set(t.date,(daily.get(t.date)||0)+t.netRtn);const dr=[...daily.values()],mu=dr.length?dr.reduce((s,x)=>s+x,0)/dr.length:0,sd=dr.length>1?Math.sqrt(dr.reduce((s,x)=>s+(x-mu)**2,0)/(dr.length-1)):0;return{trades:n,winRate:+(n?w.length/n*100:0).toFixed(1),totalReturnPct:+((eq-1)*100).toFixed(2),avgTradeBps:+(n?r.reduce((s,x)=>s+x,0)/n*10000:0).toFixed(2),profitFactor:+(gl?gp/gl:gp>0?99:0).toFixed(2),maxDrawdownPct:+(dd*100).toFixed(2),dailySharpe:+(sd?mu/sd*Math.sqrt(252):0).toFixed(2)}}
export function runNyLargeRangeContinuation(raw:Raw[]){
 const a=raw.map(norm).filter((x):x is C=>!!x).sort((x,y)=>x.time-y.time),g=new Map<string,C[]>();for(const c of a){const z=ny(c.time),q=g.get(z.date)||[];q.push(c);g.set(z.date,q)}
 const days:any[]=[];for(const[date,z0]of g){const z=z0.sort((x,y)=>x.time-y.time),op=z.filter(c=>{const m=ny(c.time).m;return m>=510&&m<540}),rest=z.filter(c=>{const m=ny(c.time).m;return m>=540&&m<960});if(op.length<2||rest.length<10)continue;const range=Math.max(...op.map(x=>x.high))-Math.min(...op.map(x=>x.low)),side:Side=op[op.length-1].close>=op[0].open?1:-1;days.push({date,time:rest[0].time,side,entry:rest[0].open,exit:rest[rest.length-1].close,range})}
 const windows=[40,60,90],costs=[.5,1,1.5],variants:any={};
 for(const win of windows)for(const cost of costs){const ts:T[]=[];const hist:number[]=[];for(const d of days){const threshold=hist.length>=win?median(hist.slice(-win)):NaN;if(Number.isFinite(threshold)&&d.range>=threshold){const gross=(d.exit-d.entry)*d.side,net=gross-cost,den=d.entry;ts.push({time:d.time,date:d.date,side:d.side,entry:d.entry,exit:d.exit,range:d.range,grossRtn:gross/den,netRtn:net/den,costPoints:cost})}hist.push(d.range)}variants[`MED${win}_COST${String(cost).replace(".","_")}PT`]=metrics(ts)}
 const core=variants.MED60_COST0_5PT,stress=variants.MED60_COST1_5PT;
 return{status:"ok",model:"NY_LARGE_RANGE_CONTINUATION_CAUSAL_V1",days:days.length,from:days[0]?.date,to:days.at(-1)?.date,rules:{signal:"08:30-09:00 NY directional impulse",gate:"opening 30m high-low >= causal median of previous 60 trading days",entry:"09:00 NY first M15 open",exit:"last M15 close before 16:00 NY",costs:"0.5 / 1.0 / 1.5 XAU points round-trip deducted",noOptimization:"MED60 is pre-frozen; MED40/90 are neighbor robustness checks only"},variants,pass:core.trades>=80&&core.avgTradeBps>1&&core.profitFactor>1.08&&stress.avgTradeBps>0,warning:"Research only. No stop/target geometry yet; this tests whether the directional edge survives point costs before spending complexity on execution."}
