type Raw=any;type C={time:number;open:number;high:number;low:number;close:number};
function mid(v:any){const b=Number(v?.bid),a=Number(v?.ask??v?.offer);return Number.isFinite(b)&&Number.isFinite(a)?(b+a)/2:Number.isFinite(b)?b:Number.isFinite(a)?a:NaN}
function prep(raw:Raw[]){return raw.map(r=>{const t=Date.parse(String(r?.snapshotTimeUTC??r?.snapshotTime??"")),o=mid(r?.openPrice),h=mid(r?.highPrice),l=mid(r?.lowPrice),c=mid(r?.closePrice);return[t,o,h,l,c].every(Number.isFinite)?{time:t,open:o,high:h,low:l,close:c}:null}).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time)}
function atr(a:C[],n=14){const o=new Array(a.length).fill(NaN);let e=NaN;for(let i=1;i<a.length;i++){const tr=Math.max(a[i].high-a[i].low,Math.abs(a[i].high-a[i-1].close),Math.abs(a[i].low-a[i-1].close));if(i<n)continue;if(i===n){let s=0;for(let j=1;j<=n;j++)s+=Math.max(a[j].high-a[j].low,Math.abs(a[j].high-a[j-1].close),Math.abs(a[j].low-a[j-1].close));e=s/n}else e=(e*(n-1)+tr)/n;o[i]=e}return o}
const sig=(z:number)=>z>=0?1/(1+Math.exp(-Math.min(30,z))):Math.exp(Math.max(-30,z))/(1+Math.exp(Math.max(-30,z)));
function dot(w:number[],x:number[]){let s=w[0];for(let i=0;i<x.length;i++)s+=w[i+1]*x[i];return s}
function feat(a:C[],A:number[],i:number){if(i<100||!Number.isFinite(A[i])||A[i]<=0)return null;const av=A[i],ret=(n:number)=>(a[i].close-a[i-n].close)/av,range=a[i].high-a[i].low||av,body=(a[i].close-a[i].open)/av,upper=(a[i].high-Math.max(a[i].open,a[i].close))/av,lower=(Math.min(a[i].open,a[i].close)-a[i].low)/av,z=a.slice(i-19,i+1),hi=Math.max(...z.map(x=>x.high)),lo=Math.min(...z.map(x=>x.low)),pos=hi>lo?2*(a[i].close-lo)/(hi-lo)-1:0;let s=0,n=0;for(let j=i-95;j<=i;j++)if(Number.isFinite(A[j])){s+=A[j];n++}const slow=n?s/n:av,d=new Date(a[i].time),phase=2*Math.PI*(d.getUTCHours()*60+d.getUTCMinutes())/1440;return[ret(1),ret(4),ret(16),ret(48),body,upper,lower,pos,av/slow-1,Math.sin(phase),Math.cos(phase),range/av-1].map(v=>Math.max(-3,Math.min(3,v)))}
function summary(ts:any[],span:number){const rs=ts.map(t=>t.net/t.entry),n=rs.length,w=rs.filter(x=>x>0),l=rs.filter(x=>x<=0),gp=w.reduce((s,x)=>s+x,0),gl=-l.reduce((s,x)=>s+x,0);let eq=1,pk=1,dd=0;for(const x of rs){eq*=1+x;pk=Math.max(pk,eq);dd=Math.max(dd,1-eq/pk)}const dm=new Map<string,number>();for(const t of ts){const k=new Date(t.exitTime).toISOString().slice(0,10);dm.set(k,(dm.get(k)||0)+t.net/t.entry)}const dr=[...dm.values()],mu=dr.length?dr.reduce((s,x)=>s+x,0)/dr.length:0,sd=dr.length>1?Math.sqrt(dr.reduce((s,x)=>s+(x-mu)**2,0)/(dr.length-1)):0;return{trades:n,winRate:+(n?w.length/n*100:0).toFixed(1),totalReturnPct:+((eq-1)*100).toFixed(2),avgTradeBps:+(n?rs.reduce((s,x)=>s+x,0)/n*10000:0).toFixed(2),profitFactor:+(gl?gp/gl:gp>0?99:0).toFixed(2),maxDrawdownPct:+(dd*100).toFixed(2),dailySharpe:+(sd?mu/sd*Math.sqrt(252):0).toFixed(2),tradesPerDay:+(n/Math.max(1,span*5/7)).toFixed(2),longs:ts.filter(t=>t.side===1).length,shorts:ts.filter(t=>t.side===-1).length,avgConfidence:+(n?ts.reduce((s,t)=>s+Math.abs(t.p-.5)*2,0)/n*100:0).toFixed(1)}}
function run(a:C[],thr:number,cost:number){const A=atr(a),w=new Array(13).fill(0),lr=.018,l2=.0008,H=4,warm=1800,out:any[]=[];let free=0,day="",cnt=0;for(let i=100;i<a.length-H-1;i++){if(i-H>=100){const x=feat(a,A,i-H);if(x){const mv=a[i].close-a[i-H].close,y=mv>0?1:0,p=sig(dot(w,x)),wt=Math.min(2,Math.max(.25,Math.abs(mv)/(A[i-H]||1))),err=(y-p)*wt;w[0]+=lr*(err-l2*w[0]);for(let k=0;k<x.length;k++)w[k+1]+=lr*(err*x[k]-l2*w[k+1])}}if(i<warm||i<free)continue;const dk=new Date(a[i].time).toISOString().slice(0,10);if(dk!==day){day=dk;cnt=0}if(cnt>=3)continue;const x=feat(a,A,i);if(!x)continue;const p=sig(dot(w,x));let side:1|-1|0=0;if(p>=thr)side=1;else if(p<=1-thr)side=-1;if(!side)continue;const entry=a[i+1].open,exit=a[i+1+H].close,gross=(exit-entry)*side;out.push({entryTime:a[i+1].time,exitTime:a[i+1+H].time,side,entry,exit,gross,net:gross-cost,p});free=i+1+H;cnt++}return out}
export function runOnlineDirectionalLab(raw:Raw[]){const a=prep(raw);if(a.length<5000)return{status:"insufficient_data",candles:a.length};const span=(a.at(-1)!.time-a[0].time)/86400000,v:any={};for(const th of [.58,.60,.62])for(const cost of [.5,1,1.5])v[`P${Math.round(th*100)}_C${String(cost).replace(".","_")}PT`]=summary(run(a,th,cost),span);const core=v.P60_C0_5PT,stress=v.P60_C1_5PT;return{status:"ok",model:"ONLINE_LOGISTIC_DIRECTIONAL_V1",candles:a.length,from:new Date(a[0].time).toISOString(),to:new Date(a.at(-1)!.time).toISOString(),rules:{learning:"causal online logistic SGD; sample updates only when 4-bar future label has matured",horizon:"1h",features:["ATR-normalized returns 15m/1h/4h/12h","body/wicks","20-bar position","ATR regime","time sin/cos","range/ATR"],entry:"next M15 open",exit:"4 bars later",threshold:"P60 frozen; P58/P62 neighbor checks",risk:"one position at a time; max 3/day",costs:"0.5/1.0/1.5 XAU points"},variants:v,pass:core.trades>=80&&core.avgTradeBps>1&&core.profitFactor>=1.08&&stress.avgTradeBps>0,warning:"Development-only online-learning test. Any candidate must be frozen before untouched older-year validation."}}
