type Raw = any;
type Side = "LONG" | "SHORT";
type TF = "M5" | "M15" | "H1";
type C = { time:number; open:number; high:number; low:number; close:number };
type Trade = { side:Side; entry:number; stop:number; take:number; r:number; result:"TP"|"SL"|"EXPIRED"; signalTime:string };

function mid(v:any){ const b=Number(v?.bid), a=Number(v?.ask??v?.offer); if(Number.isFinite(b)&&Number.isFinite(a))return(b+a)/2; if(Number.isFinite(b))return b; if(Number.isFinite(a))return a; return null; }
function norm(r:Raw):C|null{ const open=mid(r?.openPrice),high=mid(r?.highPrice),low=mid(r?.lowPrice),close=mid(r?.closePrice); const s=r?.snapshotTimeUTC??r?.snapshotTime; const time=s?Date.parse(String(s).endsWith("Z")?s:`${s}Z`):NaN; if([open,high,low,close].some(x=>x===null)||!Number.isFinite(time))return null; return {time,open:open!,high:high!,low:low!,close:close!}; }
function agg(src:C[],m:number){ const z=m*60000,out:C[]=[]; let k=-1,c:C|null=null; for(const x of src){const b=Math.floor(x.time/z)*z;if(b!==k){if(c)out.push(c);k=b;c={...x,time:b};}else if(c){c.high=Math.max(c.high,x.high);c.low=Math.min(c.low,x.low);c.close=x.close;}}if(c)out.push(c);return out;}
function done(a:C[],t:number,m:number){return a.filter(x=>x.time<=t-m*60000);}
function swings(a:C[],n=3){const hs:number[]=[],ls:number[]=[];for(let i=n;i<a.length-n;i++){let h=true,l=true;for(let j=1;j<=n;j++){if(a[i].high<=a[i-j].high||a[i].high<=a[i+j].high)h=false;if(a[i].low>=a[i-j].low||a[i].low>=a[i+j].low)l=false;}if(h)hs.push(i);if(l)ls.push(i);}return{hs,ls};}
function flow(a:C[]):Side|null{const s=swings(a.slice(-80),2); if(s.hs.length<2||s.ls.length<2)return null; const h=a.slice(-80),h1=h[s.hs.at(-1)!].high,h0=h[s.hs.at(-2)!].high,l1=h[s.ls.at(-1)!].low,l0=h[s.ls.at(-2)!].low; return h1>h0&&l1>l0?"LONG":h1<h0&&l1<l0?"SHORT":null;}
function fibZone(a:C[],side:Side){const x=a.slice(-40);if(x.length<12)return null;const hi=Math.max(...x.map(c=>c.high)),lo=Math.min(...x.map(c=>c.low)),r=hi-lo;if(r<=0)return null;const p61=side==="LONG"?hi-r*.618:lo+r*.618,p786=side==="LONG"?hi-r*.786:lo+r*.786;return[Math.min(p61,p786),Math.max(p61,p786)] as [number,number];}
function inFib(a:C[],side:Side,p:number){const z=fibZone(a,side);return !!z&&p>=z[0]&&p<=z[1];}
function fvg(a:C[],side:Side,p:number){for(let i=Math.max(2,a.length-20);i<a.length;i++){const x=a[i-2],z=a[i]; if(side==="LONG"&&x.high<z.low&&p>=x.high&&p<=z.low)return true; if(side==="SHORT"&&x.low>z.high&&p<=x.low&&p>=z.high)return true;}return false;}
function ob(a:C[],side:Side,p:number){for(let i=a.length-3;i>=Math.max(1,a.length-20);i--){const c=a[i],n=a[i+1]; if(side==="LONG"&&c.close<c.open&&n.close>c.high&&p>=c.low&&p<=c.high)return true; if(side==="SHORT"&&c.close>c.open&&n.close<c.low&&p>=c.low&&p<=c.high)return true;}return false;}
function sweep(a:C[],side:Side){if(a.length<8)return false;const s=a.at(-1)!,q=a.slice(-8,-1);return side==="LONG"?s.low<Math.min(...q.map(x=>x.low))&&s.close>Math.min(...q.map(x=>x.low)):s.high>Math.max(...q.map(x=>x.high))&&s.close<Math.max(...q.map(x=>x.high));}
function candle(a:C[],side:Side){if(a.length<2)return false;const c=a.at(-1)!,p=a.at(-2)!,body=Math.abs(c.close-c.open),rng=c.high-c.low||1;const engulf=side==="LONG"?c.close>c.open&&p.close<p.open&&c.close>=p.open&&c.open<=p.close:c.close<c.open&&p.close>p.open&&c.close<=p.open&&c.open>=p.close;const pin=side==="LONG"?(Math.min(c.open,c.close)-c.low)>body*1.5&&body/rng<.55:(c.high-Math.max(c.open,c.close))>body*1.5&&body/rng<.55;return engulf||pin;}
function bos(a:C[],side:Side){if(a.length<5)return false;const c=a.at(-1)!,q=a.slice(-5,-1);return side==="LONG"?c.close>Math.max(...q.map(x=>x.high)):c.close<Math.min(...q.map(x=>x.low));}
function m1Confirm(m1:C[],t:number,side:Side){const a=m1.filter(x=>x.time<=t).slice(-12);return a.length>=6&&(bos(a,side)||candle(a,side)||sweep(a,side));}
function metrics(ts:Trade[],days:number){const total=ts.reduce((s,t)=>s+t.r,0),w=ts.filter(t=>t.r>0),l=ts.filter(t=>t.r<0),gw=w.reduce((s,t)=>s+t.r,0),gl=Math.abs(l.reduce((s,t)=>s+t.r,0));let e=0,p=0,dd=0;for(const t of ts){e+=t.r;p=Math.max(p,e);dd=Math.max(dd,p-e);}return{trades:ts.length,tradesPerDay:+(ts.length/days).toFixed(2),winRate:ts.length?+(w.length/ts.length*100).toFixed(1):0,totalR:+total.toFixed(2),expectancyR:ts.length?+(total/ts.length).toFixed(3):0,profitFactor:gl?+(gw/gl).toFixed(2):gw?99:0,maxDrawdownR:+dd.toFixed(2)};}

const engines=[
 {id:"FLOW_OTE",name:"Fluxo + OTE defendida",ok:(x:any)=>x.h1===x.side&&x.m15===x.side&&x.fib&&(x.candle||x.sweep)&&x.bos},
 {id:"SWEEP_REVERSAL",name:"Sweep + reversão",ok:(x:any)=>x.sweep&&x.candle&&x.bos&&(x.ob||x.fvg)&&(!x.h1||x.h1!==x.side)},
 {id:"FVG_CONTINUATION",name:"Deslocamento + FVG",ok:(x:any)=>x.h1===x.side&&x.m15===x.side&&x.fvg&&x.bos&&(x.fib||x.candle)},
 {id:"OB_RETEST",name:"Order block + reteste",ok:(x:any)=>x.h1===x.side&&x.ob&&x.bos&&(x.sweep||x.candle||x.fvg)},
 {id:"LIQUIDITY_SESSION",name:"Liquidez + sessão",ok:(x:any)=>x.session&&x.sweep&&x.bos&&(x.fib||x.ob||x.fvg)&&x.candle}
];

export function runResearch(raw5:Raw[],raw1:Raw[],days=90){const m5=raw5.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m1=raw1.map(norm).filter((x):x is C=>!!x).sort((a,b)=>a.time-b.time),m15=agg(m5,15),h1=agg(m5,60);const variants:any[]=[];
for(const E of engines)for(const fibTf of ["M5","M15","H1"] as TF[])for(const useM1 of [false,true]){const trades:Trade[]=[];let blocked=-1;for(let i=100;i<m5.length-2;i++){if(i<=blocked)continue;const s=m5[i],t=s.time+300000,a15=done(m15,t,15),a1=done(h1,t,60),a5=m5.slice(0,i+1),h1f=flow(a1),m15f=flow(a15);for(const side of ["LONG","SHORT"] as Side[]){const fibA=fibTf==="M5"?a5:fibTf==="M15"?a15:a1;const hour=new Date(s.time).getUTCHours(),session=hour>=6&&hour<=20;const x={side,h1:h1f,m15:m15f,fib:inFib(fibA,side,s.close),ob:ob(a5,side,s.close)||ob(a15,side,s.close),fvg:fvg(a5,side,s.close)||fvg(a15,side,s.close),sweep:sweep(a5,side),candle:candle(a5,side),bos:bos(a5,side),session};if(!E.ok(x))continue;if(useM1&&!m1Confirm(m1,s.time,side))continue;const en=m5[i+1].open,stStruct=side==="LONG"?Math.min(...m5.slice(i-7,i+1).map(c=>c.low)):Math.max(...m5.slice(i-7,i+1).map(c=>c.high)),risk=Math.abs(en-stStruct);if(risk<=0||risk/en>.008)continue;const rr=1.5,take=side==="LONG"?en+risk*rr:en-risk*rr;let res:"TP"|"SL"|"EXPIRED"="EXPIRED",r=0,ex=Math.min(i+48,m5.length-1);for(let j=i+1;j<=ex;j++){const c=m5[j],sh=side==="LONG"?c.low<=stStruct:c.high>=stStruct,th=side==="LONG"?c.high>=take:c.low<=take;if(sh){res="SL";r=-1;ex=j;break}if(th){res="TP";r=rr;ex=j;break}}if(res==="EXPIRED"){const px=m5[ex].close;r=side==="LONG"?(px-en)/risk:(en-px)/risk;r=Math.max(-1,Math.min(rr,r));}trades.push({side,entry:en,stop:stStruct,take,r:+r.toFixed(3),result:res,signalTime:new Date(s.time).toISOString()});blocked=ex;break;}}
variants.push({engine:E.id,name:E.name,fibTimeframe:fibTf,m1Confirmation:useM1,metrics:metrics(trades,days)});}
variants.sort((a,b)=>b.metrics.expectancyR-a.metrics.expectancyR||b.metrics.totalR-a.metrics.totalR);return{methodology:{lookahead:false,movingAverages:false,minRR:1.5,fibonacci:["M5","M15","H1"],m1Tested:true,engines:engines.map(x=>({id:x.id,name:x.name}))},sample:{m5Bars:m5.length,m1Bars:m1.length,from:m5[0]?new Date(m5[0].time).toISOString():null,to:m5.at(-1)?new Date(m5.at(-1)!.time).toISOString():null},variants,best:variants.slice(0,10)};}
