import { NextRequest, NextResponse } from "next/server";
import { getHistoricalPrices, resolveGoldEpic } from "@/lib/capital";
import { runMoneyResearch } from "@/lib/money-backtest";
export const dynamic="force-dynamic"; export const maxDuration=60; const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function safe(epic:string,res:string,from:Date,to:Date){for(let a=0;a<3;a++){try{return await getHistoricalPrices(epic,res,from,to,1000)}catch(e){const m=e instanceof Error?e.message:"";if(m==="CAPITAL_API_404")return[];if(m==="CAPITAL_API_429"&&a<2){await sleep(750*(a+1));continue}throw e}}return[]}
function dedupe(out:any[]){const m=new Map<string,any>();for(const c of out){const k=String(c?.snapshotTimeUTC??c?.snapshotTime);if(k)m.set(k,c)}return[...m.values()]}
async function jobs(epic:string,res:string,js:{from:Date;to:Date}[]){const out:any[]=[];for(let i=0;i<js.length;i+=4){const p=await Promise.all(js.slice(i,i+4).map(j=>safe(epic,res,j.from,j.to)));for(const x of p)out.push(...x);if(i+4<js.length)await sleep(650)}return dedupe(out)}
async function m5(epic:string,start:Date,end:Date){const js=[] as {from:Date;to:Date}[],step=3*86400000;for(let t=start.getTime();t<end.getTime();t+=step)js.push({from:new Date(t),to:new Date(Math.min(t+step-1,end.getTime()))});return jobs(epic,"MINUTE_5",js)}
async function m1(epic:string,start:Date,end:Date){const js=[] as {from:Date;to:Date}[];for(let d=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),start.getUTCDate()));d<end;d=new Date(d.getTime()+86400000)){const wd=d.getUTCDay();if(wd===0||wd===6)continue;const a0=new Date(d.getTime()),a1=new Date(d.getTime()+9*3600000+15*60000-1),b0=new Date(d.getTime()+9*3600000+15*60000),b1=new Date(Math.min(d.getTime()+18*3600000+30*60000-1,end.getTime()));if(a1>start&&a0<end)js.push({from:new Date(Math.max(a0.getTime(),start.getTime())),to:new Date(Math.min(a1.getTime(),end.getTime()))});if(b1>start&&b0<end)js.push({from:new Date(Math.max(b0.getTime(),start.getTime())),to:b1})}return jobs(epic,"MINUTE",js)}
export async function GET(req:NextRequest){try{const offset=Math.max(0,Math.min(60,Number(req.nextUrl.searchParams.get("offset")||0)));const epic=await resolveGoldEpic(),now=new Date(),end=new Date(now.getTime()-offset*86400000),start=new Date(end.getTime()-30*86400000),startWarmup=new Date(start.getTime()-7*86400000);const raw5=await m5(epic,startWarmup,end);await sleep(700);const raw1=await m1(epic,start,end);const result=runMoneyResearch(raw5,raw1,30);return NextResponse.json({mode:"money-backtest",source:"Capital.com",epic,offsetDays:offset,window:"21:00-15:30 America/Sao_Paulo",...result},{headers:{"X-Robots-Tag":"noindex"}})}catch(e){return NextResponse.json({status:"unavailable",diagnostic:e instanceof Error?e.message:"UNKNOWN_ERROR"},{status:502})}}
